{
  "dependencies": {
    "python_class": "serializable_elist", 
    "python_module": "g_sorcery.g_collections", 
    "value": {
      "data": [], 
      "separator": "\n\t"
    }
  }, 
  "description": "An error reporting utility for ope3", 
  "eclasses": [
    "g-sorcery", 
    "gs-pypi"
  ], 
  "homepage": "http://pypi.python.org/pypi/zope.error", 
  "info": {
    "Author:": "Zope Foundation and Contributors", 
    "Categories": {
      "Development Status": [
        "5 - Production/Stable"
      ], 
      "Environment": [
        "Web Environment"
      ], 
      "Framework": [
        "Zope3"
      ], 
      "Intended Audience": [
        "Developers"
      ], 
      "License": [
        "OSI Approved", 
        "Zope Public License"
      ], 
      "Natural Language": [
        "English"
      ], 
      "Operating System": [
        "OS Independent"
      ], 
      "Programming Language": [
        "Python", 
        "3.3"
      ], 
      "Topic": [
        "Internet", 
        "WWW/HTTP"
      ]
    }, 
    "Home Page:": "http://pypi.python.org/pypi/zope.error", 
    "Keywords:": "zope3 error", 
    "License:": "ZPL 2.1", 
    "Package Index Maintainer:": "jw", 
    "Package Index Owner:": "kedder, mgedmin, projekt01, philikon, batlogg, faassen, tlotze, icemac, zagy, ccomb, agroszer, srichter, ctheune, J1m, menesis, jw, davisagli"
  }, 
  "license": "Zope Public License", 
  "longdescription": "An error reporting utility for ope3", 
  "maintainer": [
    {
      "email": "piatlicki@gmail.com", 
      "name": "Jauhien Piatlicki"
    }
  ], 
  "md5": "d18b07687a69eaf284fe32747e079165", 
  "source_uri": "https://pypi.python.org/packages/source/z/zope.error/zope.error-4.1.0.zip"
}